host {
    ip = "localhost"
    port = 1234
    protocol = https
}

strip.exif = false

file {
    mimeTypes = [ "text/html", "media/jpg" ]
    extensions = [ "mp3", "jpeg" ]
}

version = "${manifest:app-name}, version ${manifest:Implementation-Version}"